sonar.projectKey=subbu123-bantu_smart_support_main
sonar.projectName=smart_support_main
sonar.organization=subbu123-bantu
sonar.host.url=https://sonarcloud.io

sonar.sources=backend,frontend/src
sonar.tests=backend/tests,frontend/src/__tests__
sonar.inclusions=backend/**/*.py,frontend/src/**/*.js,frontend/src/**/*.jsx,frontend/src/**/*.css
sonar.test.inclusions=backend/tests/**/*.py,frontend/src/__tests__/**/*.js,frontend/src/__tests__/**/*.jsx
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/env/**,**/venv/**,**/.venv/**,**/__pycache__/**,**/.env,**/.env.*,**/*.env,**/*.env.*,**/*env.example,**/build/**,**/dist/**,**/migrations/**,backend/core/asgi.py,backend/core/wsgi.py,backend/tests/**,frontend/src/__tests__/**
sonar.scm.provider=git
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml
