sonar.projectKey=smart_support_main
sonar.projectName=smart_support_main
sonar.sources=backend/core,backend/tickets,backend/users,frontend/src
sonar.language=py
sonar.python.version=3.14
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.env,**/*.env.*,**/env/**,**/venv/**,**/__pycache__/**,**/node_modules/**,**/build/**,**/dist/**,**/.git/**,**/.vscode/**,**/migrations/**,**/backend/env/**
sonar.js.exclusions=**/node_modules/**,**/env/**,**/__pycache__/**,**/*.env*,**/.env*
sonar.python.exclusions=**/env/**,**/venv/**,**/migrations/**,**/__pycache__/**,**/*.env*
