sonar.projectKey=subbu123-bantu_smart_support_main
sonar.projectName=smart_support_main
sonar.organization=subbu123-bantu
sonar.host.url=https://sonarcloud.io

sonar.sources=backend,frontend/src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/env/**,**/venv/**,**/__pycache__/**,**/*.env,**/*.env.*,**/build/**,**/dist/**,**/migrations/**,**/tests/**
sonar.scm.provider=git
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml