CATEGORIES = ["billing", "technical", "authentication", "network", "account"]

CATEGORY_THRESHOLDS = {
    "billing": 0.82,
    "technical": 0.78,
    "authentication": 0.84,
    "network": 0.78,
    "account": 0.78,
}

PAYMENT_FAILED = "payment failed"
CHARGED_TWICE = "charged twice"
MONEY_DEDUCTED = "money deducted"
SERVER_ERROR = "server error"
ERROR_500 = "500 error"
ACCESS_DENIED = "access denied"
VERIFICATION_LINK = "verification link"
CANNOT_CONNECT = "cannot connect"
DELETE_ACCOUNT = "delete account"
NOT_WORKING = "not working"

CATEGORY_KEYWORDS = {
    "billing": [
        PAYMENT_FAILED,
        CHARGED_TWICE,
        MONEY_DEDUCTED,
        "refund not received",
        "billing issue",
        "invoice not generated",
        "wrong bill",
        "incorrectly billed",
        "subscription renewal",
        "payment deducted",
        "transaction failed",
        "overcharged",
        "refund",
        "invoice",
        "billing",
        "charged",
        "deducted",
        "subscription",
        "upi",
        "payment",
    ],
    "technical": [
        SERVER_ERROR,
        ERROR_500,
        "app crash",
        "app crashed",
        "app crashes",
        "website crash",
        "dashboard not loading",
        "white screen",
        "upload failed",
        "file upload failed",
        "loading very slowly",
        "page is loading very slowly",
        "button not working",
        "button is not working",
        "feature not responding",
        "feature response nahi de raha",
        "not responding",
        "page keeps reloading",
        "mobile view",
        "dashboard",
        "upload",
        "unexpected exception",
        "invalid response",
        "wrong data shown",
        "page broken",
        "feature not working",
        "feature not working properly",
        "report incorrect",
        "analytics wrong",
        "data mismatch",
        "crash",
        "bug",
        "broken",
        "exception",
    ],
    "authentication": [
        ACCESS_DENIED,
        VERIFICATION_LINK,
        "cannot login",
        "unable to login",
        "login failed",
        "login nahi ho raha",
        "invalid credentials",
        "account locked",
        "otp not received",
        "otp nahi aa raha",
        "password reset link",
        "session expired",
        "session expired quickly",
        "two factor authentication",
        "authentication code",
        "invalid code",
        "verification failed",
        "verify email",
        "email verification",
        "sign in",
        "locked",
        "login",
        "password",
        "otp",
        "signin",
        "verify",
        "credentials",
    ],
    "network": [
        CANNOT_CONNECT,
        "unable to connect",
        "server unreachable",
        "connection timeout",
        "request timed out",
        "network error",
        "network issue",
        "network issue aa raha hai",
        "internet issue",
        "wifi issue",
        "works on mobile data but not wifi",
        "wifi se connect nahi ho raha",
        "slow internet",
        "high latency",
        "frequent disconnect",
        "app disconnects frequently",
        "connection lost",
        "timeout",
        "latency",
        "disconnect",
        "network",
        "wifi",
        "internet",
        "connection",
    ],
    "account": [
        DELETE_ACCOUNT,
        "change email",
        "change phone",
        "update profile",
        "remove account",
        "account settings",
        "profile update",
        "account details",
        "username",
        "registered mobile",
        "registered number",
        "email address change",
        "phone number change",
        "registered phone number",
        "registered mobile number",
        "update phone number",
        "email address update",
        "account details change",
        "profile",
        "display name",
    ],
}

AUTH_DEBOOST_PHRASES = [
    "login works",
    "able to login",
    "logged in successfully",
    "can login",
]

URGENT_PHRASES = [
    "production down",
    "system down",
    "site down",
    "all users affected",
    "all users",
    "completely down",
    "cannot process payments",
    "critical issue",
    "critical",
    "immediate help",
    "immediately",
    "urgent",
    "asap",
]

GENERIC_WEAK_WORDS = {"help", "update", "issue", "problem"}

SUPPORT_HINTS = [
    "login",
    "password",
    "otp",
    "payment",
    "refund",
    "charged",
    "deducted",
    "invoice",
    "subscription",
    "dashboard",
    "upload",
    "server",
    "connection",
    "timeout",
    "network",
    "wifi",
    "profile",
    "account",
    "email",
    "phone",
    ACCESS_DENIED,
    "error",
    "crash",
    NOT_WORKING,
    "responding",
    "failed",
    "bug",
    "delete",
]
