CATEGORIES = ["billing", "technical", "authentication", "network", "account"]

CATEGORY_THRESHOLDS = {
    "billing": 0.82,
    "technical": 0.78,
    "authentication": 0.84,
    "network": 0.78,
    "account": 0.78,
}

PAYMENT_FAILED = "payment failed"
CHARGED_TWICE = "charged twice"
MONEY_DEDUCTED = "money deducted"
SERVER_ERROR = "server error"
ERROR_500 = "500 error"
ACCESS_DENIED = "access denied"
VERIFICATION_LINK = "verification link"
CANNOT_CONNECT = "cannot connect"
DELETE_ACCOUNT = "delete account"
NOT_WORKING = "not working"

CATEGORY_KEYWORDS = {
    "billing": [
        PAYMENT_FAILED,
        CHARGED_TWICE,
        MONEY_DEDUCTED,
        "refund not received",
        "billing issue",
        "invoice not generated",
        "wrong bill",
        "incorrectly billed",
        "subscription renewal",
        "payment deducted",
        "transaction failed",
        "overcharged",
        "refund",
        "invoice",
        "billing",
        "charged",
        "deducted",
        "subscription",
        "upi",
        "payment",
    ],
    "technical": [
        SERVER_ERROR,
        ERROR_500,
        "app crash",
        "app crashed",
        "website crash",
        "dashboard not loading",
        "upload failed",
        "file upload failed",
        "dashboard",
        "upload",
        "unexpected exception",
        "invalid response",
        "wrong data shown",
        "page broken",
        "feature not working",
        "report incorrect",
        "analytics wrong",
        "data mismatch",
        "crash",
        "bug",
        "broken",
        "exception",
    ],
    "authentication": [
        ACCESS_DENIED,
        VERIFICATION_LINK,
        "cannot login",
        "unable to login",
        "login failed",
        "invalid credentials",
        "account locked",
        "otp not received",
        "password reset link",
        "session expired",
        "verification failed",
        "verify email",
        "email verification",
        "sign in",
        "locked",
        "login",
        "password",
        "otp",
        "signin",
        "verify",
        "credentials",
    ],
    "network": [
        CANNOT_CONNECT,
        "unable to connect",
        "server unreachable",
        "connection timeout",
        "request timed out",
        "network error",
        "internet issue",
        "wifi issue",
        "slow internet",
        "high latency",
        "frequent disconnect",
        "connection lost",
        "timeout",
        "latency",
        "disconnect",
        "network",
        "wifi",
        "internet",
        "connection",
    ],
    "account": [
        DELETE_ACCOUNT,
        "change email",
        "change phone",
        "update profile",
        "remove account",
        "account settings",
        "profile update",
        "registered number",
        "email address change",
        "phone number change",
        "registered phone number",
        "registered mobile number",
        "update phone number",
        "profile",
        "display name",
    ],
}

AUTH_DEBOOST_PHRASES = [
    "login works",
    "able to login",
    "logged in successfully",
    "can login",
]

URGENT_PHRASES = [
    "production down",
    "system down",
    "site down",
    "all users affected",
    "cannot process payments",
    "critical issue",
    "urgent",
    "asap",
]

GENERIC_WEAK_WORDS = {"help", "update", "issue", "problem"}

SUPPORT_HINTS = [
    "login",
    "password",
    "otp",
    "payment",
    "refund",
    "charged",
    "deducted",
    "invoice",
    "subscription",
    "dashboard",
    "upload",
    "server",
    "connection",
    "timeout",
    "network",
    "wifi",
    "profile",
    "account",
    "email",
    "phone",
    ACCESS_DENIED,
    "error",
    "crash",
    NOT_WORKING,
    "failed",
    "bug",
    "delete",
]