# Generated by Django 6.0.3 on 2026-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketstatus_remove_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
        migrations.DeleteModel(
            name='TicketStatus',
        ),
    ]
