# Generated by Django 6.0.3 on 2026-03-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_description_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id']},
        ),
    ]
