# Generated by Django 6.0.3 on 2026-03-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In_progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
