# Generated by Django 6.0.3 on 2026-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_user_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_ticket_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
