# Generated by Django 6.0.3 on 2026-03-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_user_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('billing', 'Billing'), ('authentication', 'Authentication'), ('network', 'Network'), ('account', 'Account'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
