# Generated by Django 6.0.3 on 2026-03-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_options_ticket_auto_assigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('predicted_category', models.CharField(max_length=50)),
                ('predicted_priority', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('final_accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
