# Generated by Django 6.0.3 on 2026-03-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticketpredictionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
