# Generated by Django 6.0.3 on 2026-03-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticket_assigned_team_ticket_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='auto_assigned',
        ),
    ]
