# Generated by Django 6.0.3 on 2026-03-30 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticket_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_team',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='predicted_category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='predicted_priority',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user_ticket_id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
