# Generated by Django 6.0.3 on 2026-03-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticket_options_ticket_assigned_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='predicted_category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='predicted_priority',
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='predicted_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='predicted_priority',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
