# Generated by Django 6.0.3 on 2026-03-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_remove_ticket_predicted_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='predicted_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='predicted_priority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
