# Generated by Django 6.0.3 on 2026-04-01 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_alter_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='embedding',
        ),
        migrations.AddField(
            model_name='ticketpredictionlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
