# Generated by Django 6.0.3 on 2026-04-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_remove_ticket_embedding_ticketpredictionlog_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='final_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
