# Generated by Django 6.0.3 on 2026-04-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_ticketpredictionlog_final_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_ticket_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
