# Generated by Django 6.0.3 on 2026-04-09 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_ticketcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpredictionlog',
            name='final_accepted',
        ),
        migrations.AddField(
            model_name='ticketpredictionlog',
            name='actual_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketpredictionlog',
            name='actual_priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketpredictionlog',
            name='category_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketpredictionlog',
            name='priority_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='predicted_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='predicted_priority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket'),
        ),
    ]
