# Generated by Django 6.0.3 on 2026-04-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_remove_ticketpredictionlog_final_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='predicted_category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='predicted_priority',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='actual_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='actual_priority',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='category_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='priority_correct',
            field=models.BooleanField(default=False),
        ),
    ]