# Generated by Django 6.0.3 on 2026-04-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_alter_ticket_predicted_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='category_correct',
            field=models.BooleanField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='priority_correct',
            field=models.BooleanField(blank=True, default=''),
        ),
    ]
