# Generated by Django 6.0.3 on 2026-04-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_alter_ticketpredictionlog_category_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='actual_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='actual_priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='category_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='priority_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
