# Generated by Django 6.0.3 on 2026-04-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_alter_ticketpredictionlog_actual_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='actual_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketpredictionlog',
            name='actual_priority',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
