# Generated by Django 6.0.3 on 2026-04-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_alter_ticketpredictionlog_actual_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_team',
        ),
    ]
