# Generated by Django 5.2.11 on 2026-03-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('customer', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
