# Generated by Django 6.0.3 on 2026-03-31 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_remove_ticket_predicted_category_and_more'),
        ('users', '0004_alter_user_role_agentprofile_delete_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='skill_tags',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='categories',
            field=models.ManyToManyField(to='tickets.category'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
