# Generated by Django 6.0.3 on 2026-04-02 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_alter_ticketpredictionlog_final_accepted'),
        ('users', '0008_alter_agentprofile_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.category'),
        ),
    ]
