# Generated by Django 6.0.3 on 2026-04-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
    ]
