# Generated by Django 6.0.3 on 2026-04-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='categories',
        ),
    ]
