# Generated by Django 6.0.3 on 2026-04-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_ticketcomment'),
        ('users', '0011_remove_agentprofile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, to='tickets.category'),
        ),
    ]
