# Generated by Django 6.0.3 on 2026-04-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_agentprofile_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
